# Generated by Django 2.1.1 on 2018-09-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
