# Generated by Django 2.1.1 on 2018-09-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='adress',
            field=models.URLField(blank=True, null=True),
        ),
    ]
