# Generated by Django 2.1.1 on 2018-09-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='logo',
            field=models.ImageField(default='Logo.png', upload_to=''),
        ),
    ]
