# Generated by Django 2.1.1 on 2018-09-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180927_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='adress',
        ),
        migrations.AlterField(
            model_name='post',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
